version: '3'
services:
  property-damage-recognition-db:
    container_name: property-damage-recognition-db
    image: 'mysql'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"